services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  meteor:
    image: geoffreybooth/meteor-base:2.12
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/meteor
      - PORT=3000
    depends_on:
      - mongo

volumes:
  mongo-data: